version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=$OPENAI_KEY

  client:
    build:
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro