name: build-app
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Static Render and Compress for Prompt
        run: |
          cd client
          npm install
          npm run build
          npm run render
          cd npx ts-node ../scripts/compress.ts ./dist/ ../server/src/prompts/projectDescription.txt

      - name: Build And Deploy Docker Images
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-add ~/.ssh/deploy_key
          echo "${{ secrets.HOST_ENTRIES }}" > ~/.ssh/known_hosts
          export DOCKER_HOST=ssh://dockeruser@129.213.48.213
          docker-compose up --build -d